apiVersion: v1
kind: Service
metadata:
  name: device-management
spec:
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: device-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: device-management
  template:
    metadata:
      labels:
        app: device-management
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: device-management
          image: device-management:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL_MGMT
# Probes disabled for stability
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8002
#            initialDelaySeconds: 15
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 8002
#            initialDelaySeconds: 5
#            periodSeconds: 10
