apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: management
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          # Note: In production we would use a ConfigMap for rabbitmq-plugins
          command:
            [
              "/bin/sh",
              "-c",
              "echo 'loopback_users = none' > /etc/rabbitmq/rabbitmq.conf && rabbitmq-plugins enable rabbitmq_mqtt && rabbitmq-server",
            ]
          ports:
            - containerPort: 5672
            - containerPort: 1883
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASSWORD
